# Generated by Django 3.0.2 on 2020-05-09 04:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_tracker', '0002_auto_20200502_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=9)),
                ('pre_add', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('income', 'income'), ('expense', 'expense'), ('tranfer', 'tranfer')], max_length=7)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=30)),
                ('create_on', models.DateField(default=datetime.date.today)),
                ('balance', models.IntegerField()),
                ('add_to_total', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('pre_add', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_account_set_up',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_account',
        ),
        migrations.DeleteModel(
            name='User_account_set_up',
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.FinanceProfile'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_tracker.Category'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_tracker.Subcategory'),
        ),
        migrations.AddField(
            model_name='accountsubcategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.FinanceProfile'),
        ),
        migrations.AddField(
            model_name='accountsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.Subcategory'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.Category'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.FinanceProfile'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.FinanceProfile'),
        ),
    ]
