# Generated by Django 3.0.2 on 2020-05-09 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_auto_20200509_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.FinanceProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_tracker.Account'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=7),
        ),
        migrations.CreateModel(
            name='ExpenseTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='expense_tracker.Account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.FinanceProfile')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='expense_tracker.Account')),
            ],
        ),
    ]
