# Generated by Django 3.0.2 on 2020-05-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0005_auto_20200509_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransfer',
            name='note',
            field=models.CharField(default='initial', max_length=30),
            preserve_default=False,
        ),
    ]
