# Generated by Django 3.0.2 on 2020-06-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0006_expensetransfer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='home', max_length=20),
        ),
    ]
