# Generated by Django 3.0.3 on 2020-02-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='current',
            field=models.CharField(choices=[('True', 'displayed'), ('False', 'not displayed')], default='displayed', max_length=5),
        ),
    ]
