# Generated by Django 3.0.3 on 2020-02-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_announcement_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='current',
            new_name='current_announcement',
        ),
    ]
