# Generated by Django 3.0.2 on 2020-02-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200207_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='current_announcement',
            field=models.CharField(choices=[('True', 'displayed'), ('False', 'not displayed')], default='Flase', max_length=5),
        ),
    ]
