# Generated by Django 3.0.2 on 2020-06-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app_log')),
                ('create_on', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_log.App_list')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
