# Generated by Django 3.0.2 on 2020-02-22 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worktracker', '0003_auto_20200219_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('tittle', models.CharField(max_length=30)),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('type', models.CharField(choices=[('work', 'work'), ('project', 'project'), ('life', 'life')], max_length=7)),
                ('description', models.TextField(default=None, null=True)),
                ('notes', models.TextField(default=None, null=True)),
                ('ending', models.TextField(default=None, null=True)),
                ('tags', models.TextField(default=None, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('isparent', models.IntegerField(default=0)),
                ('timetaken', models.DurationField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
