# Generated by Django 3.0.2 on 2020-02-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timetaken',
            field=models.DurationField(default='seconds=27'),
        ),
    ]
