# Generated by Django 3.0.2 on 2020-02-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0005_auto_20200222_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timetaken',
            field=models.DurationField(null=True),
        ),
    ]
