# Generated by Django 3.0.2 on 2020-02-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0008_task_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
