# Generated by Django 3.0.2 on 2020-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0011_auto_20200223_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
