# Generated by Django 3.0.2 on 2020-02-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0012_userstat_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='temp_start',
            field=models.DateTimeField(null=True),
        ),
    ]
