# Generated by Django 3.0.2 on 2020-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0013_task_temp_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timetaken',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
