# Generated by Django 3.0.2 on 2020-02-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0015_auto_20200223_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_data',
            name='time_spent',
        ),
    ]
