# Generated by Django 3.0.2 on 2020-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0016_remove_login_data_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timetaken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
