# Generated by Django 3.0.2 on 2020-03-10 13:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worktracker', '0017_auto_20200226_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('lunch_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_on', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
