# Generated by Django 3.0.2 on 2020-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0018_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='lunch_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='lunch_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
