# Generated by Django 3.0.2 on 2020-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0021_userstat_current_side_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='current_side_track',
            field=models.TextField(default='show_sidetrack_list', null=True),
        ),
    ]
